### PR TITLE
Fixed #117 and one more bug in ChainedHashTable

### LINKED ISSUE #117: ChainedHashTable test sometimes fail
**Describe the bug**
During development some other feature, and run frequently "dotnet test" i notice that some test connected to ChainedHashTable sometimes pass sometimes not. Problem also occur on clear master branch. 

**To Reproduce**
Run dotnet test command many times, that test doesn't crash every time.

**Expected behavior**
Test should always pass.

**Additional context**
  X UnitTest.DataStructuresTests.HashTableSeparateChainingTest.DoTest [61ms]
  Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at DataStructures.Dictionaries.ChainedHashTable`2.CopyTo(KeyValuePair`2[] array, Int32 arrayIndex) in D:\repositories\public\C-Sharp-Algorithms\DataStructures\Dictionaries\ChainedHashTable.cs:line 609
   at UnitTest.DataStructuresTests.HashTableSeparateChainingTest.DoTest() in D:\repositories\public\C-Sharp-Algorithms\UnitTest\DataStructuresTests\HashTableSeparateChainingTest.cs:line 107

### PR DESCRIPTION
**Pull request by Gutsonok**
### Description

1) Fix #117 . This bug occurs when hash table has collisions. Then the hashTable node contain a list with some values. And the method CopyTo try to fill an array by the end using values from list in this node.
I added check for existing the next element in the list in the hashTable node.

2) I divided a unit test for ChainedHashTable on some tests. And added additinal tests.

3) When i added unit tests i had found a new bug. 
When a user create two or greater ChainedHashTable objects then these objects have the same LinkedList array for storing values i.e. adding new value to one hash table this value add to another hash tables.
I add creating a new array for every ChainedHashTable objects in constructor.

### CODE REVIEW

File: UnitTest/DataStructuresTests/HashTableSeparateChainingTest.cs [hunk 1]
```diff
@@ -7,107 +9,134 @@ namespace UnitTest.DataStructuresTests
...
+        public static void Adding_TwoDuplicateElements_ReturnsException()
+        {
+            var studentsMarks = new ChainedHashTable<string, int>();
+            studentsMarks.Add("Name1", 1);
+            studentsMarks.Add("Name2", 5);
+
+            Action act = () => studentsMarks.Add("Name2", 7);
+            
+            var exception = Assert.Throws<ArgumentException>(act);
+            Assert.Equal("Key already exists in the hash table.", exception.Message);
```
Comment (aalhour) [inline UnitTest/DataStructuresTests/HashTableSeparateChainingTest.cs]: Can you add an assertion for `studentsMarks.Count == 1`, here?

File: UnitTest/DataStructuresTests/HashTableSeparateChainingTest.cs [hunk 2]
```diff
@@ -7,107 +9,134 @@ namespace UnitTest.DataStructuresTests
...
+
+            var array = new KeyValuePair<string, int>[studentsMarks.Count];
+            studentsMarks.CopyTo(array, 0);
+
+            Assert.True(studentsMarks.Count == 3);
+            Assert.True(array.Length == 3);
+            var arrayKeys = array.Select(x => x.Key).OrderBy(x => x).ToArray();
+            Assert.Equal("Name1", arrayKeys[0]);
+            Assert.Equal("Name2", arrayKeys[1]);
+            Assert.Equal("Name3", arrayKeys[2]);
```
Comment (aalhour) [inline UnitTest/DataStructuresTests/HashTableSeparateChainingTest.cs]: Can you add a similar assertions chain for the values as well?

**Comment by Gutsonok** [comment]
> 
> 
> Refactoring LGTM, we just need to add a few more assertions to the unit tests.

I have added assertions for these unit tests.
